### ISSUE TITLE
Incorrect dependencies for different python versions?

### ISSUE THREAD

**Issue by varundey** [Sandeeprds95/result-reminder#1]
bs4 is Python2 module and urllib.request is Python3 module. I first tried running it on my Linux system with proper changes made to path variables, but it showed error `ImportError: No module named request`. I then tried running it with python3 and it showed `ImportError: No module named 'bs4'.`

I searched online for the issue and found that bs4 is Python2 exclusive module and urllib.request is Python3 exclusive. I think I have all the required dependencies. Am I missing something here?

**Comment by Sandeeprds95** [comment]
I use Python3 on my system. I have not encountered any such problem till now.
http://www.crummy.com/software/BeautifulSoup/
This link, under the downloads section says, it works well for Python2 and above, including Python3 being explicitly mentioned.
I guess you have an older version of BeautifulSoup? Try updating it.

**Comment by Sandeeprds95** [comment]
Did it clear your problem?

**Comment by varundey** [comment]
Yes. However updating BeaustifulSoup didnt solve the problem. I had to dig deep and found that bs4 for python3 resides in different path and thus has to be installed explicitly using `sudo apt-get install python3-bs4` :v:

**Comment by Sandeeprds95** [comment]
Okay, cool. Glad your problem got solved.
